### PR TITLE
Never print to stdout, always use stderr

### PR DESCRIPTION
**Pull request by Jille**
This makes it possible to use deepface in programs that use stdout for other usages. For example I use it in a streaming pipeline that outputs the represent results on stdout.

### CODE REVIEW

**Comment by Jille** [comment]
Keras still seems to print some stuff to stdout, I've yet to track down how to move that to stderr.

**Comment by serengil** [comment]
those information are not error. they are printed to system out intendedly.

**Comment by Jille** [comment]
stderr is for diagnostic messages, not necessarily errors.

https://stackoverflow.com/questions/3385201/confused-about-stdin-stdout-and-stderr has a lot of background

**Comment by Andrea-Oliveri** [comment]
Good morning,
@Jille, if this is still an issue for you, you may want to use contextlib to redirect the stdout to stderr or to any other stream.

**Pull request closed without merging**
