### PR TITLE
added option to detect multiple faces in detectFace

### PR DESCRIPTION
**Pull request by iakshat**
Hi!
I wanted to detect multiple faces in an image but the library didn't offer any support for multiple face detection. Detecting multiple faces in the images might be a use case for other developers too!

I've run unit_test.py and attached the output : [unit_tests.txt](https://github.com/serengil/deepface/files/7936099/unit_tests.txt)

PS: I am not a pro. Please suggest any design changes if it can be done in a better way!

### CODE REVIEW

**Comment by medmen** [comment]
Hi, 

this looks a lot like a thing I was looking for .
Unfortunately I am a python-noob, so I wont be of help a lot.  
I fixed my needs by using a function @serengil implemented in retinaface ([https://github.com/serengil/retinaface/blob/master/retinaface/RetinaFace.py])
@serengil: could you possibly port that function to deepface?

Let me explain my motivation: I am trying to add name tags to my photo collection. I am using shotwell on Ubuntu and thats a feature I am missing

**Comment by serengil** [comment]
Sure, I will do a code review and merge it soon.

**Comment by alessandrolamberti** [comment]
> Sure, I will do a code review and merge it soon.

Any update on this?

**Review by zacharyseid — APPROVED** [review]

**Comment by serengil** [comment]
this feature covered in the new release by default

**Pull request closed without merging**
