### PR TITLE
Add MediapipeWrapper as a detector

### PR DESCRIPTION
**Pull request by blueprintparadise**
Mediapipe is a google powered face detection API. The detector is extremely fast and reliable.
Necessary changes to the FaceDetectorWrapper.py and requirements.txt have also been made.
Please consider adding this to your awesome project.

P.S - 
This is my first contribution to an open-source project and I might have accidentally committed some error,
Feel free to change the file as you wish and criticize my work, I am still a novice and have much to learn.
Cheers, BPP.

### CODE REVIEW

**Comment by serengil** [comment]
Thank you for your contribution

But I cannot run mediapipe when I try. It waits forever!

**Comment by blueprintparadise** [comment]
I tried redoing everything on my end and it seems to work fine.
Does the error you encounter occur in the build_model phase or the detect_face phase?

**Comment by serengil** [comment]
it is waiting in model building stage.

**Comment by bhky** [comment]
Hello!
I have tried this branch and confirmed that the changes work fine one my side, e.g., by simply doing
```
from deepface import DeepFace
DeepFace.analyze("my_image.jpg", backend_detector="mediapipe")
```

In fact, this is fantastic as Mediapipe is really fast. Thanks @blueprintparadise !

@serengil , could you advise how to re-produce your problem? Thanks!

**Comment by blueprintparadise** [comment]
I have been trying for a while to understand the problem but could not. Glad to know it works fine for you.
@serengil , could you help us?

**Comment by bhky** [comment]
Hi @blueprintparadise! 
Please also check that, it is needed to do, e.g.,
```
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
```
before calling `process` from the Mediapipe model, as it expects RGB images.
Thanks! :slightly_smiling_face:

**Comment by serengil** [comment]
it just waits. no error message I got.

**Comment by lavrenkov-sketch** [comment]
Hello!
I have tried this mediapipe and confirmed that the changes work fine without bugs and problems

**Comment by uriafranko** [comment]
Hey,

Keep in mind that Mediapipe doesn't support Apple's M1 yet, and DeepFace will lose support as well.
Unless it will be on a separate release.

**Comment by serengil** [comment]
unfortunately, I cannot merge this PR until test it on my mac (intel processor)

**Comment by serengil** [comment]
I merged the PR. Sorry for the delay and thank you for the contribution.

**Comment by serengil** [comment]
@blueprintparadise I am not able to test mediapipe detector on my mac and found the reason here: https://github.com/google/mediapipe/issues/1461

It seems that once tf imported first, then mediapipe hangs

I'm going to open an issue to mediapipe

**Pull request merged**
