### PR TITLE
refactor: simplify the inception resnet v2 model definition code

### PR DESCRIPTION
**Pull request by bpradana**
### What has been done

With this PR, I have simplify the code for InceptionResNetV2 model. I remove the repetition in the code and replace it with for loop for better readbility

## How to test

I have compare it with the original code and it performs exactly the same

### CODE REVIEW

**Comment by serengil** [comment]
I converted from loop approach to that one already. Because I found this is more legible. Thank you but I prefer not to merge this.

**Comment by bpradana** [comment]
thank you for the feedback!

**Comment by AndreaLanfranchi** [comment]
Hey @bpradana I am interested into your pr.
Would open a PR in my repo ?

**Comment by bpradana** [comment]
@AndreaLanfranchi sure!

**Pull request closed without merging**
