### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by Fadeleke57**
## Tickets

https://github.com/serengil/deepface/issues/XXX

### What has been done

Should be good

### CODE REVIEW

**Comment by serengil** [comment]
LGTM

**Comment by serengil** [comment]
Question: should not it be less than tensorflow 2.13?

I mean I suppose this should still work for tf 2.12.1?

**Comment by serengil** [comment]
Realized that dependency is just used for deepface model, so instead of enforcing tf version, I decided to check tf version in that model's initialization in this PR: https://github.com/serengil/deepface/pull/1083

**Comment by Fadeleke57** [comment]
Good solution!

**Pull request merged**
