### PR TITLE
Fix bug with unicode filenames

### PR DESCRIPTION
**Pull request by RayVik**
If used on a database images with unicode filenames, opencv will be raise with error

### CODE REVIEW

**Comment by serengil** [comment]
this does not behave same with imread.

```python
import cv2
import numpy as np

img_path = "dataset/img1.jpg"

img1 = cv2.imread(img_path)

img2 = open(img_path, "rb")
chunk = img2.read()
img2 = np.frombuffer(chunk, dtype=np.uint8)

assert np.array_equal(img1, img2) == True
```

**Comment by RayVik** [comment]
You miss
```python
img2 = cv2.imdecode(img2, cv2.IMREAD_COLOR)
``` 
Must be
```python
import cv2
import numpy as np

img_path = "dataset/img1.jpg"

img1 = cv2.imread(img_path)

img2 = open(img_path, "rb")
chunk = img2.read()
img2 = np.frombuffer(chunk, dtype=np.uint8)
img2 = cv2.imdecode(img2, cv2.IMREAD_COLOR)

assert np.array_equal(img1, img2) == True
```

**Comment by serengil** [comment]
instead of removing following line, would you please deactivate it and add comment "this causes troubles when reading files with non english names". i will merge it when pipeline completed successfully.

```python
return cv2.imread(img)
```

**Comment by serengil** [comment]
unfortunately, your code does not satisfy linting requirements: https://github.com/serengil/deepface/actions/runs/4832336779/jobs/8611143293

deepface/commons/functions.py:105:0: C0303: Trailing whitespace (trailing-whitespace)

this cannot be merged until pipeline succeeded

**Comment by serengil** [comment]
thank you for your contribution

**Pull request merged**
