### PR TITLE
update: replace existing face detection model with YOLOv11n-face

### PR DESCRIPTION
**Pull request by angelusbr**
- Updated weights path to support YOLOv11n-face
- Added integration for YOLOv11n-face model for improved face detection performance
- Weights hosted at: https://github.com/akanametov/yolo-face

## Tickets

This update addresses the feature request and issue discussed in [#1392](https://github.com/serengil/deepface/issues/1392).

### What has been done

This PR introduces YOLOv11n-face as the new model for face detection, offering the following improvements:

- Updated weights path: The previous face detection model has been replaced with the YOLOv11n-face weights for better accuracy.
- Improved performance: YOLOv11n-face provides faster inference and higher precision in detecting faces, particularly beneficial in real-time applications.
- Optimized for edge devices: YOLOv11n is designed for enhanced performance on resource-constrained devices, making it ideal for deployment on low-power devices or in cloud-based systems.

### CODE REVIEW

**Comment by angelusbr** [comment]
Makes sense, I agree.

**Comment by angelusbr** [comment]
Should I create a Yolo11.py file and rename Yolo.py to Yolo8.py?

**Comment by serengil** [comment]
We can store both v8 and v11 in same file. Don't recommend to duplicate code.

**Comment by angelusbr** [comment]
I was changing the Yolo.py file but [#1394](https://github.com/serengil/deepface/issues/1392) occurred, preventing me from testing the new code.

**Comment by serengil** [comment]
I closed that issue because it is not a bug, instead in purpose

**Comment by serengil** [comment]
Duplicated - https://github.com/serengil/deepface/pull/1397

**Pull request closed without merging**
