### PR TITLE
Correct laterality of the eyes landmarks ("close" #741)

### PR DESCRIPTION
**Pull request by Vincent-Stragier**
Hi,

In https://github.com/serengil/deepface/issues/741, I noticed an error on the alignment. After further investigation, I noticed the error was in the mediapipe's wrapper. The eyes landmarks are permuted. There is head for improvement in other models (at least the one able to detect faced at any angle), like using a third poind (nose, mouth, etc.) to correctly realized the rotation.

Regards,
Vincent

### CODE REVIEW

**Comment by serengil** [comment]
add some comments

**Comment by Vincent-Stragier** [comment]
Hi,

I'd be happy to comment, but I don't really know what to add here. I changed the "no result" guard, and the landmarks for the left and right eyes were permuted.

You can add (GitHub) comments in the PR, where I should elaborate my changes.

Regards,
Vincent

**Comment by Vincent-Stragier** [comment]
Hi @serengil,

Any news on my previous comment? I'm waiting on this PR to be merged before working on #757 and #758.

Kind regards,
Vincent

**Comment by Vincent-Stragier** [comment]
@serengil,

This PR should be ready to merge, as well as PR #757. And #758 will have conflicts to resolve with `DeepFace.py`, but I'll fix them when this PR and #757 will be merged.

Regards,
Vincent

**Pull request merged**
