### PR TITLE
Tests workflow

### PR DESCRIPTION
**Pull request by onuratakan**
Hello, i added tests workflow, witht this update some commits and pr will be check automatic with unit_tests.py.

- Added a gitignore that for ignoring pyc
- unit_tests.py converted to unittest testcase
- Added tests workflow that include lint test and unit test

You shoul merge this pr with squash method.

Best regards,

Onur Atakan ULUSOY

### CODE REVIEW

**Comment by onuratakan** [comment]
With this update you can add a badge to readme with this code

[Tests](https://github.com/serengil/deepface/actions/workflows/tests.yml)

**Comment by serengil** [comment]
I did not run units test in each commit in purpose because I commit this project a lot

**Comment by onuratakan** [comment]
İt gonna be edit for different situations but i think the pr and commits need an tests that running automatical

**Comment by onuratakan** [comment]
Also the tests are running in some commit and pr example if you edit the readme the test are not working again.

**Comment by onuratakan** [comment]
@serengil Hello again, please try this its will be a speed up for development process and contributions.
With your new test system ı dont have to do anything on your unit_test py

The tests are running in changes of these directories/files:
      - '.github/workflows/tests.yml'
      - 'deepface/**'  
      - 'tests/**'
      - 'api/**'
      - 'requirements.txt'
      - '.gitignore'
      - 'setup.py'

**Comment by serengil** [comment]
@onuratakan thank you for your contribution

**Pull request merged**
