### PR TITLE
Fix yunet return negative coordinates

### PR DESCRIPTION
**Pull request by AnthraX1**
Yunet returns negative coordinates if it thinks part of the detected face is outside the frame. This fixes that by reset the start point to zero.

### CODE REVIEW

**Comment by serengil** [comment]
pylint fails. would you please fix them.

```
************* Module deepface.detectors.YunetWrapper
deepface/detectors/YunetWrapper.py:58:8: R1731: Consider using 'x = max(x, 0)' instead of unnecessary if block (consider-using-max-builtin)
deepface/detectors/YunetWrapper.py:60:8: R1731: Consider using 'y = max(y, 0)' instead of unnecessary if block (consider-using-max-builtin)
```

**Comment by serengil** [comment]
also, adding a comment would be good in that line why we did it.

**Comment by AnthraX1** [comment]
> also, adding a comment would be good in that line why we did it.

done

**Comment by AnthraX1** [comment]
> This time fails because of this:
> 
> deepface/detectors/YunetWrapper.py:59:0: C0301: Line too long (105/100) (line-too-long)

It was complaining about the wrong line but the new commit should fix it.

**Comment by serengil** [comment]
************* Module deepface.detectors.YunetWrapper
deepface/detectors/YunetWrapper.py:61:65: C0303: Trailing whitespace (trailing-whitespace)
deepface/detectors/YunetWrapper.py:47:8: W0105: String statement has no effect (pointless-string-statement)

**Comment by AnthraX1** [comment]
finally passed all checks...

**Pull request merged**
