### PR TITLE
Load models to memory

### PR DESCRIPTION
**Pull request by uriafranko**
2 new functions:
analyze_init(models = []):
verify_init(model_name = 'VGG-Face')

The functions created in order to pre-load models to memory for shorter analzye / verify first time
Ex:
Real time analyze waiting for first face to show.
without analyze_init()
first analyze takes 1.5 sec
with analyze_init()
first analyze takes 0.3 sec

### CODE REVIEW

**Comment by serengil** [comment]
Hello,

Thank you for your contribution. You plan to call verify_init and then verify function in your program?

```
DeepFace.verify_init(model_name='VGG-Face')
DeepFace.verify("1.jpg", "2.jpg", model_name='VGG-Face')
```

Because you can pass already built model to verify function. If so, verify_init might return the built model and then you pass this model to verify function. 

```
model = DeepFace.verify_init(model_name='VGG-Face')
DeepFace.verify("1.jpg", "2.jpg", model_name='VGG-Face', model = model)
```

**Comment by serengil** [comment]
BTW, should we add these init functions into the interface really? The following code block covers this already for verify function. However, I have to add this logic into the analyze function as well.

```
from deepface import DeepFace
from deepface.basemodels import VGGFace
model = VGGFace.loadModel()
result = DeepFace.verify("img1.jpg", "img2.jpg", model_name = "VGG-Face", model = model)
```

**Comment by serengil** [comment]
So, modifications you did in analyze function cover a gap in the framework. However, I do not think that verify_init and analyze_init functions necessary. Could you remove those init functions and send a new pull request?

**Comment by uriafranko** [comment]
I wonder if I should add some local docs for the new models dict in the analyze func 
let me know I will add some quick

**Comment by serengil** [comment]
You mean adding some information in read me?

**Comment by serengil** [comment]
I merged your pull request to the master branch. Really appreciate.

**Pull request merged**
