### PR TITLE
Pass custom path argument while loading model

### PR DESCRIPTION
**Pull request by NISH1001**
Add `model_path` parameter in `loadModel()` function. This adds more
flexiblity while loading the models, especially when we want to containerize our custom application that may use deepface library.

Also, refactor code using standard `os.path.join` which will make sure
to join the paths correctly.

### CODE REVIEW

**Comment by serengil** [comment]
did you run tests/unit_tests.py?

**Comment by serengil** [comment]
I cloned the latest version of your commits. It does not work unfortunately.

(tensorflow) C:\Users\IS96273\Desktop\deepface\tests>python unit_tests.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "unit_tests.py", line 1, in <module>
    from deepface import DeepFace
  File "c:\users\is96273\desktop\deepface\deepface\DeepFace.py", line 20, in <module>
    from deepface.basemodels import VGGFace, OpenFace, Facenet, FbDeepFace
  File "c:\users\is96273\desktop\deepface\deepface\basemodels\VGGFace.py", line 81
    print(f"vgg_face_weights.h5 will be downloaded to {model_path}")
                                                                  ^
SyntaxError: invalid syntax

**Comment by NISH1001** [comment]
What python version are you using? The f-style string formatting syntax is fairly standard but new. Is there a minimal version that the project requires? If f-style is syntax error, I can change that to old style.

**Comment by NISH1001** [comment]
Also, I haven't run the tests...but fairly ran the changes on my custom scripts to test the models (including loading parts).

**Comment by serengil** [comment]
setup py requires min python 3.5.5.

please confirm unit tests are running as well.

**Pull request closed without merging**
