### PR TITLE
Close #532, add docstring and some refactoring.

### LINKED ISSUE #532: load_image is not same from url or from file
```python
# in colab
from deepface.commons import functions
import numpy as np
url = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/MontreGousset001.jpg/440px-MontreGousset001.jpg"
file = "440px-MontreGousset001.jpg"
!wget {url} -O {file} -q

img_from_url = functions.load_image(url)
img_from_file = functions.load_image(file)

print(np.abs(img_from_url-img_from_file).mean())
# 98.4184350027692
```

https://github.com/serengil/deepface/blob/ba9f56755abdc9d1d80777d7680c4267d5d5e0e9/deepface/commons/functions.py#L85-L92
The reason is because you convert the image to RBG with url
And for file, you use cv2.imread, the default setting is rgb

Please align those two methods

### PR DESCRIPTION
**Pull request by Vincent-Stragier**

### CODE REVIEW

**Comment by serengil** [comment]
adding docstrings are fine but i dislike to mention input arg types and return of a function. this is not a must in python. please exclude these type controls.

**Comment by Vincent-Stragier** [comment]
I can also edit the docstrings if needed. They were meanly auto-generated by Copilot (I quickly checked each of them).

**Comment by serengil** [comment]
I run the github actions. Will merge this as is if it passes unit tests and linting stuff.

**Comment by serengil** [comment]
Your PR fails in linting - https://github.com/serengil/deepface/actions/runs/4303315857/jobs/7503204289

```
Run pylint --fail-under=10 deepface/
  
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.BaseException' ?) instead.
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.Exception' ?) instead.
************* Module deepface.commons.functions
deepface/commons/functions.py:101:0: C0301: Line too long (110/100) (line-too-long)
deepface/commons/functions.py:128:0: C0301: Line too long (102/100) (line-too-long)
deepface/commons/functions.py:130:0: C0301: Line too long (10[7](https://github.com/serengil/deepface/actions/runs/4303315857/jobs/7503204289#step:5:7)/100) (line-too-long)
deepface/commons/functions.py:236:0: C0301: Line too long (109/100) (line-too-long)
deepface/commons/functions.py:91:4: R1[7](https://github.com/serengil/deepface/actions/runs/4303315857/jobs/7503204289#step:5:8)05: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)

-----------------------------------
Your code has been rated at [9](https://github.com/serengil/deepface/actions/runs/4303315857/jobs/7503204289#step:5:10).97/[10](https://github.com/serengil/deepface/actions/runs/4303315857/jobs/7503204289#step:5:11)
```

These warning must be resolved before merging.

**Comment by serengil** [comment]
thank you for contribution

**Pull request merged**
