### PR TITLE
Added docker file

### LINKED ISSUE #394: Docker file base image for deepface on windoes
Hi, I am struggling with errors for docker file built giving me errors.
Can you help me with docker file for running deepface on a windows machine?

### PR DESCRIPTION
**Pull request by onuratakan**
closes #394 

# Explaination
Hello again, its a good feature for deepface because now deepface library work on every machine without any problem. We love you docker =).

# For building and using:

## Building
```console
docker build -t deepface .
```
## Using
```console
docker run -it deepface /bin/sh
```
### With Volume
With this run command argument you can access your files in container (the volumes files will be in db directory of container, you can access there)
```console
-v deepface:/db
```

## With Network (For api)
With this run command argument you can use the api outside of container
```console
--network=host
```

### CODE REVIEW

**Comment by serengil** [comment]
thank you for your contribution

**Comment by minimalisticMe** [comment]
For someone who is not familiar with docker, how would I start `api/api.py` in the docker image?
Thank you very much in advance.

**Comment by onuratakan** [comment]
> For someone who is not familiar with docker, how would I start `api/api.py` in the docker image? Thank you very much in advance.

After building the docker container, you can write to this command after accessing the bash with this "docker run -it deepface /bin/sh"

```console
python3 api/api.py
```

**Comment by minimalisticMe** [comment]
Thank you very much, that's super easy and helpful 👍

**Pull request merged**
