### PR TITLE
Loads MTCNN once only + convert to RGB before inferenence + add better readibility

### PR DESCRIPTION
**Pull request by ma7555**
This builds the MTCNN network only once for faster inference

### CODE REVIEW

**Comment by serengil** [comment]
Thank you for your contribution. It seems a huge pull request. I have to test unit tests before merge it. It might take a while. I'll inform you.

**Comment by ma7555** [comment]
Sure, take your time and if you needed any help let me know.

**Comment by serengil** [comment]
load_mtcnn seems missing in the analyze and detectFace functions.

**Comment by serengil** [comment]
I merged yhe pull request. Thank you for your contribution.

**Comment by ma7555** [comment]
thank you, I have fixed the other functions too along with faster batched inference for both images to compare.

Please have a look and if you want, I can open a new PR

**Comment by serengil** [comment]
I fixed it already :) Besides, I created a new function to initialize all detectors not just mtcnn.

**Pull request merged**
